version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Current directory contents before copying:"
      - ls -al
      - echo "Building the website"
      - mkdir -p build
      - echo "Copying files to build directory..."
      - cp -r ./* build/ || echo "Copy command failed"  # add error handling
      - echo "Contents of build directory after copying:"
      - ls -al build/
artifacts:
  files:
    - '**/*'
