version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Current directory contents:"
      - ls -al
      - echo "Building the website"
      - mkdir -p build
      - cp -r ./* build/
      - echo "Build completed successfully."
artifacts:
  files:
    - '**/*'
